-- Add email and enabled flags for users
ALTER TABLE users ADD COLUMN email VARCHAR(255);
ALTER TABLE users ADD COLUMN enabled BOOLEAN DEFAULT FALSE;

-- Backfill sample users with emails and enable them
UPDATE users SET email = CONCAT(username, '@example.com'), enabled = TRUE WHERE email IS NULL;

-- Add confirmation tokens table
CREATE TABLE confirmation_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(64) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_confirmation_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_confirmation_token_user ON confirmation_tokens(user_id);
